
# Pandas- DataFrame And Series

Pandas is a powerful data manipulation library in Python, widely used for data cleaning. It provides two primary data structures. DataFrame and structures: Series and dataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional,size-mutable, and potentially hetrogeneous tabular data structure with labeled axes (rows and columns).

In [ ]:
import pandas as pd

In [ ]:
## Series
## Pandas Series is a one-dimensional array-like onject that can hold any data type. It is similar to a column in a table.

import pandas as pd
data=[1,2,3,4,5]
series = pd.Series(data)
print(series)
print(type(series))
print("Series \n",series)

In [ ]:
# Create a series from dictionary
data={"a":1,"b":2,"c":3}
series_dict =pd.Series(data) 
print(series_dict)

In [ ]:
data = [10,20,30]
index = ["a","b","c"]
pd.Series(data,index=index)

In [12]:
## Dataframe
## Create a DataFrame from a dictionary of lists

data = {
    "Name":['Krish','John','Harry'],
    "Age":[25,30,45],
    "city":['Banglore','New York','Florida']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      city
0  Krish   25  Banglore
1   John   30  New York
2  Harry   45   Florida
<class 'pandas.DataFrame'>

In [37]:
## Create a DataFrame from a list of Dictionaries

data = [
    {"Name":"Krish","Age":25,"City":"Banglore"},
    {"Name":"John","Age":32,"City":"Banglore"},
    {"Name":"Bappy","Age":25,"City":"Banglore"},
    {"Name":"Jack","Age":25,"City":"Banglore"}
]

df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  Krish   25  Banglore
1   John   32  Banglore
2  Bappy   25  Banglore
3   Jack   25  Banglore
<class 'pandas.DataFrame'>

In [38]:
df = pd.read_csv("sales_data.csv")
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [43]:
# Display the data types of each column
print("Data types:\n",df.dtypes)

# Describe the Dataframe
print("Describe:\n",df.describe())

# Group by a column and perform an aggregation 
grouped = df.groupby("Product Category")["Total Revenue"].mean()
print("Mean value by category:\n",grouped)

Data types:
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object
Describe:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000
Mean value by category:
 Product Category
Beauty Products     65.54750
Books               46.54825
Clothing           203.22325
Electronics        874.56025
Home Appliances    466.15400
Sports             358.16300
Name: Total Revenue, dtype: float64

In [44]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [ ]:
df.tail(5)

In [17]:
# Accessing a specified element

df.at[2,"Name"]

'Harry'

In [19]:
## Acdessing a specified element using iat
df.iat[2,2]

'Florida'

In [20]:
### Data manipulation with dataframes

df

    Name  Age      city
0  Krish   25  Banglore
1   John   30  New York
2  Harry   45   Florida

In [36]:
# Adding a column
df["Salary"]=[50000,60000,70000]
df

    Name  Age      city  Salary
0  Krish    2  Banglore   50000
1   John    2  New York   60000
2  Harry    2   Florida   70000

In [27]:
## Remove a column

df.drop("Salary",axis=1,inplace = True)

KeyError: "['Salary'] not found in axis"

In [35]:
df

    Name  Age      city
0  Krish    2  Banglore
1   John    2  New York
2  Harry    2   Florida

In [34]:
## Add age to the column after a year

df["Age"]= df["Age"]+1
df

    Name  Age      city
0  Krish    2  Banglore
1   John    2  New York
2  Harry    2   Florida